services:
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: watchtower_db
    restart: always
    environment:
      POSTGRES_USER: "watchtower"
      POSTGRES_PASSWORD: "CHANGEME"
      POSTGRES_DB: "watchtower"
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - watchtower_db_volume:/var/lib/postgresql/data
    networks:
      - watchtower_net
  
  dashboard:
    image: grafana/grafana:main-distroless-slim
    container_name: watchtower_dashboard
    restart: unless-stopped
    user: "0:0"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboard:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    networks:
      - watchtower_net
    depends_on:
      - db
  
  server:
    image: busybox:1.38.0
    container_name: watchtower_server
    restart: unless-stopped
    volumes:
      - ./config/server.yaml:/etc/watchtower/server.yaml
      - ./build/watchtower_server:/opt/watchtower/bin/watchtower_server
      - ./certs/ca:/opt/watchtower/tls/ca
      - ./certs/server:/opt/watchtower/tls/server
      - ./src:/opt/watchtower/src
    command: ["/opt/watchtower/bin/watchtower_server"]
    network_mode: "host"
    depends_on:
      - db

volumes:
  watchtower_db_volume:

networks:
  watchtower_net:
    driver: bridge