agent:
  push_interval_seconds: 30
  server_url: "https://0.0.0.0:443"
  name: "test1"
  verbose: true
tls:
  ca_cert: "/opt/watchtower/tls/ca/ca.crt"
  agent_cert: "/opt/watchtower/tls/server_agent/agent.crt"
  agent_key: "/opt/watchtower/tls/server_agent/agent.key"