agent:
  push_interval_seconds: 30
  server_url: "https://0.0.0.0:443"
  name: "test1"
  verbose: true
tls:
  ca_cert: "/opt/watchtower/tls/ca/ca.crt"
  agent_cert: "/opt/watchtower/tls/agent/test_agent.crt"
  agent_key: "/opt/watchtower/tls/agent/test_agent.key"