agent:
  push_interval_seconds: 30
  server_url: "https://0.0.0.0:443"
  name: "test1"
  verbose: true

tls:
  ca_cert: "/etc/watchtower/tls/ca.crt"
  agent_cert: "/etc/watchtower/tls/agent.crt"
  agent_key: "/etc/watchtower/tls/agent.key"